# You don't need any database setup for this demo. The manifest
# uses Keycloak's development mode (start-dev command) which:

# - Uses an embedded H2 database (in-memory)
# - Automatically handles all database initialization
# - Perfect for demos and testing
# - Data won't persist between pod restarts (which is fine for demos)

# The manifest will work completely as-is without any external
# database configuration. Just deploy and it's ready to use.

# SSL Certificate Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
  namespace: default
type: kubernetes.io/tls
data:
  # Self-signed certificate for demo purposes
  # In production, use proper certificates from a CA
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4RENDQWRnQ0NRRE1tZmp0aE1PSmNEQU5CZ2txaGtpRzl3MEJBUXNGQURBNk1Rc3dDUVlEVlFRR0V3SlYKVXpFUU1BNEdBMVVFQ2d3SGMyOXNieTVwYnpFWk1CY0dBMVVFQXd3UWEyVjVZMnh2WVdzdVpHVm1ZWFZzZERBZQpGdzB5TlRBNU1UY3hNek0zTURWYUZ3MHlOakE1TVRjeE16TTNNRFZhTURveEN6QUpCZ05WQkFZVEFsVlRNUkF3CkRnWURWUVFLREFkemIyeHZMbWx2TVJrd0Z3WURWUVFEREJCclpYbGpiRzloYXk1a1pXWmhkV3gwTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBc2NTQUEyaTNnc1E2T2pQczAyQ2NjSVQzaitGbApFdGNyTCtVMFozd2x1dFpvR1Z6em1QUmFkeWw1L1ppZy9acy9rNzByRVVYb09jVC9aeTk2bWFBaE5KdDhHTHcvCk9UcXcyWittYit1Z3RoYTFITDBCMGczTXNIYTVrMzYzaGpYZmJZc09McHNlZ0ZjYkpBdFBOREJSWHhKU3lwVGcKQlhUQnpoeWxUSnFwcDgrdGtzREF3YmVMckpLVFZwdlVSeVNsb0pKYUZQRG1qRkNySi9VN0tVVVBEL1VCeUpjeAprYjNrRjcyckZ0TmFDZ0lGdmdqTHUzSndLZ0k1dStuL3FaRVJQMllmUkFHdGhzOUVtWDVqdjc2OE02SEpPTmRjCklwU1YyRnMzcStGUVVOK0lqMkNabTFIczU3dDdJNEZmVmVydFVpQjJncUFHcXVuRVFieVdPbzdNdndJREFRQUIKTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT0tyOFp4dm52NzlWWjg1cGNSMGNBSEwxdU5FcGFieGtJYVZyYgpYTmcxZjY0clE4VmdzSWZTRkJROHdiQjBtQjRCSXhOYVFVUEZtVHRLczBZejdONTRVWEVhVUxFTFlDUFZrUkhPClNPajNVUjNiUUFubnlrWDBWbHp5bm1tTUVUUVF6dUpBUnUvS1hyWmt0b1BJRllLaWpLbW1Fc3o4UG1TcjltNXcKcUo0eThkNTRURElHczlYT0Ixa1M4NXpZajhrc2thVHpnd2kwVFg2WkhacmprQmk4K05ncHRJeWlSWnRQTkxONAptU0lHUjF3TlJvZENTN1hVZEM4T3NpQ1A0aEdhdmhPSmJwNWN4VDlZMCtBdnVRY2lTY0NucFo3L2g5MCtDN2psCkxvb1k0QzN4WVM0VnFZMzlNWVU5NHJ5UTdBZldSYUMyN3FNTHZ6NmhmN2M1WW9ITwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3h4SUFEYUxlQ3hEbzYKTSt6VFlKeHdoUGVQNFdVUzF5c3Y1VFJuZkNXNjFtZ1pYUE9ZOUZwM0tYbjltS0Q5bXorVHZTc1JSZWc1eFA5bgpMM1Fab0NFMG0zd1l2RDg1T3JEWm42WnY2NkMyRnJVY3ZRSFNEY3l3ZHJtVGZyZUdOZDl0aXc0dW14NkFWeHNrCkMwODBNRkZmRWxMS2xPQUZkTUhPSEtWTW1xbW56NjJTd01EQnQ0dXNrcE5XbTlSSEpLV2drbG9VOE9hTVVLc24KOVRzcFJROFA5UUhJbHpHUnZlUVh2YXNXMDFvS0FnVytDTXU3Y25BcUFqbTc2Zitwa1JFL1poOUVBYTJHejBTWgpmbU8vdnJ3em9jazQxMXdpbEpYWVd6ZXI0VkJRMzRpUFlKbWJVZXpudTNzamdWOVY2dTFTSUhhQ29BYXE2Y1JCCnZKWTZqc3kvQWdNQkFBRUNnZ0VBYm9jcXdQUGZCZU5VQU5SQUw3MG1CNS9rL1FTN2YxZGhkc29nSnllOW5jbXAKdC90ZlNuN0RzTXVOR2V4SVRPYTJSUG1kU1lRWnU3R015Mjl0M3c3OUZtU0dhQ3JEZEtYVlI3cElGZFovZWpmcwpMQTRvajU0YzRxc3UvMUlPY2RnVkwxc0NXbUFBT3ZQdDRCOVlBNjczS1JHUGdIM0lQQnc0VkJyamZCbTkycVB3Cmk5NXZ6SW0zNE1JUDRBSXlwZFE1NlFlSlduRGhtbWlkYkVMNlZzSVVJdzVVMGtyNVR4eTUvZlh3eWpRMi9yTXoKRTFpV3hpZ09nQm1FTnkvSFBKVk1teFJVVzk4RGlLLzUyVTV2WmZFQ2NNUUlESm13UDhHUXRTemVnTXpjUFZVWgplSmxlL3BLQ2xYRXZIUDNwNFZwYXJSMlB4QjBUTk90a2EwOTdpelUxNFFLQmdRRFl5VnN4Vk4wK2FlZWJRd0xsCi9LbjNMU2krQnRqWlkxbG1FN1ZnRExjRDh6QzJoOVpNYjlzbzJyemhjR3RwOERhRkhZcmtHVXNpdEpISklXZUwKV0tGemlHU0R2WjhRTFRwMVNDTUFVbDN4UmNtQzhNSEtkb01kR2JvalZNNU42RHJxUXZpWEZxamVnbEVLWThHTwpqZGxFTGtYb0tzK0Vib3REL2U2YzVxNU85UUtCZ1FEUjdFOEx1WmNtMGl4bytSSjM0TDB0WC9wWUEvcEZvYm9oCkl6bDAzeHYxdURTemxzelZsc0M1TmdSd2ZOV2w4dUU2a3N4TUhINTVnc0lQY2tCU2FkWW0zMVdMcERmeWtWK0UKcGZmWUFOYTV4M3NXVGVkTW13czJHNHpnZkg4Mmc4WnRBZnB4L3R2QzdrejhDQVJUdzVnb0dibU9BWHpIbFEvYwpVdzhrdGRxMFl3S0JnUUNVcVZCZC9nSlNZTEd3NlQwOWxnekFNam0wUm1IQ2dieTJvV0ZKNHI1R2lTaW9vM0l6CnJLa3YxUUNkNEVmb3VBL0xMVDBudXFpcHZnWVRWVkw2WGVjcG9TaThwdlpEVTZDNCtLVDMvWVBxaHA3dnFrWmEKbnZhK3AvdmJhcmFtK2xBY2daeVRqN2h5RGcrZy9sT25mR0szdkx1M3dGUGFUeXcxamhkcGhVK1hXUUtCZ0Z6RgpwVzFXR01HMFVxSVZxUjdIZUhOc0hqUDFsZzVkMmVjNUxQUkVnWlBIVTZzbWN1SFYzTmc5VWhyd1lHOFZkb292ClJCQkM2M1lCM29kN0E0Z29jOWI4RGs5SFJONXpkcFlsenZGcjlYbG0rak95UEEwejIvR09uV1M4UUhBMExtWVEKWU1FdVU2ckRLOHlhTW1kZVlva2VUVTIveEloampQM2V5eXQ3SHV0bkFvR0FLWUF2LzYzQXdHbXdZaHRocnc1MApPS0RjU0s0RVErSUcwZHl4WjFIVldPeHlQN2xWNGxZbkFLUTdzdWV0aXYzdTZyMzYwN0ZyNFFhQmlYbkhtNW5VCjJRNEN6NWo4c3JremRCNnNObWxNS3YxMGZqelhJK3d4ZU9WYjZmaXNnMGhDMTJnQWdYSmdvWWI2N25DUGtEbS8KbEFVeVdkcjFmVDI4RnZJK2FCMEo3d0k9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/ssl/tls.crt"
  KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/ssl/tls.key"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.3
        args: ["start-dev"]
        envFrom:
        - configMapRef:
            name: keycloak-config
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: keycloak-tls
          mountPath: /opt/keycloak/ssl
          readOnly: true
      volumes:
      - name: keycloak-tls
        secret:
          secretName: keycloak-tls

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: keycloak
  type: LoadBalancer